output:
	clang++ -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -fno-jump-tables -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -target-cpu x86-64 -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -nostdsysteminc -nobuiltininc -resource-dir lib/clang/11.0.1 -isystem /usr/lib/clang/include -include /usr/src/linux-headers-5.13.0-28/include/linux/kconfig.h -include /usr/include/bcc/bpf.h -include /usr/include/bcc/helpers.h -isystem /usr/include -isystem /usr/src/linux-headers-5.13.0-28/include/ -I /home/parmmath/Documents/bpftracer/skbtracer -D __BPF_TRACING__ -I arch/x86/include/ -I arch/x86/include/generated -I include -I arch/x86/include/uapi -I arch/x86/include/generated/uapi -I include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -D KBUILD_MODNAME="bcc" -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /usr/src/linux-headers-5.13.0-28-generic -ferror-limit 19 -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -faddrsig -o main.bc -x c /home/parmmath/Documents/bpftracer/skbtracer/tracer.cpp

tracer:
	clang++ -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -fno-jump-tables -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -target-cpu x86-64 -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -nostdsysteminc -nobuiltininc -resource-dir lib/clang/11.0.1 -x c++ -isystem /usr/lib/clang/include -include /usr/include/linux/bpf.h -include /usr/lib/llvm-13/lib/clang/13.0.0/include/stddef.h -isystem /usr/src/linux-headers-5.13.0-28/include/ -isystem /usr/include/x86_64-linux-gnu/ -isystem /usr/include -isystem /usr/lib/llvm-13/lib/clang/13.0.0/include/ -isystem /usr/include/c++/11/ -isystem /usr/include/x86_64-linux-gnu/c++/11/ -I /home/parmmath/Documents/bpftracer/skbtracer -D __BPF_TRACING__ -I arch/x86/include/ -I arch/x86/include/generated -I include -I arch/x86/include/uapi -I arch/x86/include/generated/uapi -I include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -D KBUILD_MODNAME="bcc" -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /usr/src/linux-headers-5.13.0-28-generic -ferror-limit 19 -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -faddrsig -o main.bc -x c /home/parmmath/Documents/bpftracer/skbtracer/tracer.cpp

newtracer:
	g++ x86_64-unknown-linux-gnu -lstdc++ -std=c99 -emit-llvm-bc -emit-llvm-uselists -da -fno-jump-tables -fmath-errno -fno-rounding-math -isystem /usr/lib/clang/include -include /usr/include/linux/bpf.h -isystem /usr/include/x86_64-linux-gnu/ -isystem /usr/include/ -isystem /usr/include/c++/11/ -isystem /usr/include/x86_64-linux-gnu/c++/11/ -I /home/parmmath/Documents/bpftracer/skbtracer/ -D __BPF_TRACING__ -I arch/x86/include/ -I arch/x86/include/generated -I include -I arch/x86/include/uapi -I arch/x86/include/generated/uapi -I include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -D KBUILD_MODNAME="bcc" -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -o main.bc -x c /home/parmmath/Documents/bpftracer/skbtracer/tracer.cpp

plain:
	clang++ -resource-dir lib/clang/11.0.1 -x c++ -isystem /usr/lib/clang/include -include /usr/include/linux/bpf.h -include /usr/lib/llvm-13/lib/clang/13.0.0/include/stddef.h -isystem /usr/src/linux-headers-5.13.0-28/include/ -isystem /usr/include/x86_64-linux-gnu/ -isystem /usr/include -isystem /usr/lib/llvm-13/lib/clang/13.0.0/include/ -isystem /usr/include/c++/11/ -isystem /usr/include/x86_64-linux-gnu/c++/11/ -I /home/parmmath/Documents/bpftracer/skbtracer -D __BPF_TRACING__ -I arch/x86/include/ -I arch/x86/include/generated -I include -I arch/x86/include/uapi -I arch/x86/include/generated/uapi -I include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -D KBUILD_MODNAME="bcc" -O2 -o main.bc /home/parmmath/Documents/bpftracer/skbtracer/tracer.cpp

# $ bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
# $ clang -g -O2 -target bpf -D__TARGET_ARCH_x86_64 -I . -c hello.bpf.c -o hello.bpf.o
# $ bpftool gen skeleton hello.bpf.o > hello.skel.h
# $ clang -g -O2 -Wall -I . -c hello.c -o hello.o
# $ clang -Wall -O2 -g hello.o libbpf/build/libbpf.a -lelf -lz -o hello
# $ sudo ./hello